### ISSUE TITLE
no-parameter-properties is deprecated

### ISSUE THREAD

**Issue by breucode** [astoilkov/eslint-config-strictest#1]
According to https://typescript-eslint.io/rules/no-parameter-properties/ this rule is deprecated and should be replaced with https://typescript-eslint.io/rules/parameter-properties

Thanks for this nice plugin btw, it helps me a lot to learn typescript and it prevents adopting bad style.

**Comment by astoilkov** [comment]
Awesome! I will make the change soon. Thanks!
